# Generated by Django 4.0.5 on 2022-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
