# Generated by Django 4.0.5 on 2022-06-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_noticias', '0002_alter_noticia_data_alteracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='data_alteracao',
        ),
    ]
